"""002_auth

Revision ID: 87ff312e2a56
Revises: ce9effa4bfdd
Create Date: 2026-06-18 10:43:57.778950
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87ff312e2a56'
down_revision: Union[str, None] = 'ce9effa4bfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Código interno del rol (ej: admin, profesor, alumno)'),
    sa.Column('nombre', sa.String(length=255), nullable=False, comment='Nombre legible del rol (ej: Administrador, Profesor)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_role_tenant_code')
    )
    op.create_index('ix_role_tenant_deleted', 'role', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_role_tenant_id'), 'role', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('email_encrypted', sa.Text(), nullable=False, comment='Email cifrado AES-256-GCM (ciphertext en base64)'),
    sa.Column('email_lookup', sa.String(length=64), nullable=False, comment='HMAC determinístico del email para búsqueda única'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash Argon2id de la contraseña'),
    sa.Column('legajo', sa.String(length=50), nullable=True, comment='Legajo del alumno (atributo de negocio, NO credencial)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email_lookup', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_user_email_lookup'), 'user', ['email_lookup'], unique=False)
    op.create_index('ix_user_tenant_deleted', 'user', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 del token de reseteo (nunca el token en claro)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Momento de uso del token; NULL = no usado aún'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_token_tenant_deleted', 'password_reset_token', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_password_reset_token_tenant_id'), 'password_reset_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_user_id'), 'password_reset_token', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 del token refresh (nunca el token en claro)'),
    sa.Column('family_id', sa.UUID(), nullable=False, comment='Identificador de familia: agrupa tokens de la misma sesión'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_token_tenant_deleted', 'refresh_token', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_tenant_id'), 'refresh_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('totp_secret',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK única: un usuario solo puede tener un secreto TOTP activo'),
    sa.Column('secret_encrypted', sa.Text(), nullable=False, comment='Secreto TOTP cifrado AES-256-GCM (nunca en claro)'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Momento en que el usuario confirmó la configuración 2FA'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_totp_secret_tenant_deleted', 'totp_secret', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_totp_secret_tenant_id'), 'totp_secret', ['tenant_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('desde', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hasta', sa.DateTime(timezone=True), nullable=True, comment='NULL = vigente; con fecha = desactivado desde ese momento'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'tenant_id', 'desde')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_totp_secret_tenant_id'), table_name='totp_secret')
    op.drop_index('ix_totp_secret_tenant_deleted', table_name='totp_secret')
    op.drop_table('totp_secret')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_tenant_id'), table_name='refresh_token')
    op.drop_index('ix_refresh_token_tenant_deleted', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_password_reset_token_user_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_tenant_id'), table_name='password_reset_token')
    op.drop_index('ix_password_reset_token_tenant_deleted', table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index('ix_user_tenant_deleted', table_name='user')
    op.drop_index(op.f('ix_user_email_lookup'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_tenant_id'), table_name='role')
    op.drop_index('ix_role_tenant_deleted', table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
